### ISSUE TITLE
feature: improve module naming for testing

### ISSUE THREAD

**Issue by guidosarducci** [dtaht/fq_codel_fast#1]
Hi Dave,
I've been curious to try out your changes. Just a suggestion, but if you renamed the built module (and I guess internal `.id` too) as "fast_fq_codel" instead of the current "fq_codel", it would be easier to have the old/new modules coexist and also simplify A/B testing. And both should still trigger the same regexes within sqm-scripts for their tc args.

Thanks!

**Comment by dtaht** [comment]
Well, I didn't want to have to change tc also.

**Comment by guidosarducci** [comment]
Ahh, I see, so the `tc` operations and qdisc identities are indexed based on the `.id`? And so even distinct modules (e.g. sch_fq_codel.ko and sch_fast_fq_codel.ko) require a unique `.id`? If that's the case then we can live with removing/inserting modules to switch between the two, but wouldn't that require a custom OpenWrt kernel, since by default `sch_fq_codel` is built-in and not dynamic?

Maybe it's just best to ask how you do your own A/B testing?

**Comment by dtaht** [comment]
x86_64 on an apu2 running ubuntu. My days of building openwrt from scratch ended with cerowrt - too burned out. I am irked enough about a couple things in openwrt to *want* to build it again, but I would rather upgrade my deployment and look for a dayjob at the moment.

**Comment by dtaht** [comment]
the roadmap for making a multicore outbound shaper is clear but fixing the inbound path... oy...

**Comment by guidosarducci** [comment]
Yeah, understood.  I presume I was right about needing unique `.id`s above... Ubuntu and x86 is the way to go -- `fq_codel` is a module by default, and you don't end up devoting your time to narrow optimizations targeting an anemic MIPS platform. :slightly_frowning_face:

It *has* become easier to reliably re-build and reproduce OpenWrt versions without borking unintended aspects. Still, I would just ignore those irksome bits unless you're trying to fix a real in-kernel issue.

Best of luck on the day job.
