### ISSUE TITLE
Inverted logic for applying sce?

### ISSUE THREAD

**Issue by tohojo** [dtaht/fq_codel_fast#2]
Isn't the check for a valid sce_param inverted here?

https://github.com/dtaht/fq_codel_fast/blob/b6d9bd85d7f1f49a565934e47f03a0ba872449f5/codel_impl.h#L245

I.e., it should be `skb && params->sce_threshold && ...` ?

**Comment by dtaht** [comment]
I can't tell what the truth is at 3AM

**Comment by dtaht** [comment]
no.

**Comment by heistp** [comment]
Here are packet counts with the original version:

$ ./analyze.sh 
ECN=0x00: 5996 packets
ECN=0x01: 0 packets
ECN=0x02: 33 packets
ECN=0x03: 5970 packets

and with params->sce_threshold instead of !params->sce_threshold:

sysadmin@rey:~/src/fqf_test$ ./analyze.sh 
ECN=0x00: 3064 packets
ECN=0x01: 0 packets
ECN=0x02: 6053 packets
ECN=0x03: 0 packets

So I think the original version is right(?) With that version, I'm seeing calls to INET_ECN_set_sce and IP_ECN_SET_sce, only no packets have ECN==0x01.

**Comment by dtaht** [comment]
do a pull as jon committed something that might be right

**Comment by heistp** [comment]
Already at b6d9bd85.

**Comment by dtaht** [comment]
printk is called for

**Comment by heistp** [comment]
It breaks it, but if I just set the tos field directly in IP_ECN_set_sce I start getting packets with ECN==0x01:

iph->tos = INET_ECN_ECT_1;

**Comment by chromi** [comment]
Found the problem and pushed a fix.

**Comment by heistp** [comment]
Yes, that's it:

$ ./analyze.sh 
ECN=0x00: 4174 packets
ECN=0x01: 8259 packets
ECN=0x02: 3 packets
ECN=0x03: 0 packets

**Comment by dtaht** [comment]
/me is gonna cry with joy. Why no CE?

Can we defer public speculation on how to fix all the tcps in the world, and diffserv until late next week, and just focus on getting the code running and tested everywhere we can? :)

We can fix tcp at liesure. Next up is to determine if flipping these bits so often causes any observable re-ordering across the internet. 

adding sce_threshold to cake needs a new parameter for iproute2 and stats.

there's also fq_pie (at least the bsd version) and fq_codel there too - and it too needs an equivalent of sce.h

**Comment by chromi** [comment]
> On 16 Mar, 2019, at 3:48 pm, Dave Täht <notifications@github.com> wrote:
> 
> Why no CE?

TCP Short Queues in action, maybe?

**Comment by heistp** [comment]
Also, I sent you ce_threshold 1us. With ce_threshold 1ms things look quite different:

$ ./analyze.sh 
ECN=0x00: 4175 packets
ECN=0x01: 0 packets
ECN=0x02: 8262 packets
ECN=0x03: 0 packets

**Comment by dtaht** [comment]
I'm setting ce_threshold to 1us
I just rebooted the server

**Comment by dtaht** [comment]
My test is 

flent -H 172.104.129.160 -t whatever --socket-stats --te=download_streams=100 -l 20 tcp_ndown

that should defeat tsq handily

**Comment by heistp** [comment]
Ok, with ce_threshold 1us and iperf3 -P 32 (32 flows):

$ ./analyze.sh 
ECN=0x00: 6856 packets
ECN=0x01: 252 packets
ECN=0x02: 18 packets
ECN=0x03: 5973 packets

**Comment by dtaht** [comment]
That's kind of weird, but ok.

**Comment by dtaht** [comment]
Us making an assertion that sce would work based on the riteprojects reasearch that the bits would be preserved e2e kind of made me nervous, given the quality of their other work. I'd done intense source code inspection on every os I could inspect but field middlebox behavior is kind of unknown.

Did not see these bits set on that and e2e test but I may have goofed. Thinking

**Comment by heistp** [comment]
It's surprising to me that I have to set ce_threshold as low as 1us to get SCE marks. I don't see any with even 2us. But as long as that makes sense to someone. :)

I'll change my analyze script to count ECN marks separately in each direction and try it over the Internet.

**Comment by dtaht** [comment]
It doesn't. rounding error?

**Comment by heistp** [comment]
If I've got fq_codel_fast on egress and am testing an upload to an iperf3 server (still local, not over Internet), shouldn't ECN=0x01 be returned from the receiver?

$ sudo ./analyze.sh 
ECN=0x00 up: 516 packets
ECN=0x00 down: 8259 packets
ECN=0x01 up: 451 packets
ECN=0x01 down: 1 packets
ECN=0x02 up: 5 packets
ECN=0x02 down: 6 packets
ECN=0x03 up: 7396 packets
ECN=0x03 down: 29 packets

**Comment by dtaht** [comment]
I setup sqm for 20mbits on that server with ce_threshold 10us. 

It works!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by dtaht** [comment]
[tcp_ndown-2019-03-16T143124.337505.sqm_ce_threshold_9us.flent.gz](https://github.com/dtaht/fq_codel_fast/files/2973978/tcp_ndown-2019-03-16T143124.337505.sqm_ce_threshold_9us.flent.gz)

**Comment by dtaht** [comment]
http://flent-newark.bufferbloat.net/~d/sce/sqm.cap :woot:

**Comment by heistp** [comment]
The actual value for q->cparams.sce_threshold is only > 0 if you specify > 1us, I guess due to CoDel's 1024nsec clock thing. So I actually only get SCE marks if the internal ce_threshold value is 0.

Also, for your sqm.cap:

$ ./analyze.sh sqm.cap 
ECN==0x00 up: 33519 packets
ECN==0x00 down: 615 packets
ECN==0x01 up: 61 packets
ECN==0x01 down: 1206 packets
ECN==0x02 up: 155 packets
ECN==0x02 down: 334 packets
ECN==0x03 up: 41 packets
ECN==0x03 down: 31284 packets

**Comment by chromi** [comment]
> On 16 Mar, 2019, at 4:45 pm, Pete Heist <notifications@github.com> wrote:
> 
> The actual value for q->cparams.sce_threshold is only > 0 if you specify > 1us, I guess due to CoDel's 1024nsec clock thing. So I actually only get SCE marks if the internal ce_threshold value is 0.

I just fixed that.  Because 1us gets rounded down to zero, you'll need to specify 2us or more.

**Comment by heistp** [comment]
Thank you sir, that does it. :) Finally SCE marks, even at 10ms:

$ ./analyze.sh 
ECN==0x00 up: 519 packets
ECN==0x00 down: 8222 packets
ECN==0x01 up: 425 packets
ECN==0x01 down: 0 packets
ECN==0x02 up: 29 packets
ECN==0x02 down: 6 packets
ECN==0x03 up: 7385 packets
ECN==0x03 down: 29 packets
